import './globals.css'
import { Manrope } from 'next/font/google'
import Script from 'next/script'
import { Footer } from '@/components'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        {children}
        <Footer />
        <Script src="https://kit.fontawesome.com/72aeedc907.js" />
      </body>
    </html>
  )
}
